### ISSUE TITLE
Investigate and potentially fix the multi-threading issue with decoding using the klauspost leopard implementation.\

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/rsmt2d#123]
When parallelising the crossword loop, it works fine with infectious, but errors on go-leopard and klauspost leopard. Seems like a potential issue with doing parallel decodings. Otherwise, it resulted in 4x+ performance increase for 128x128 blocks with infectious.

Branch with parallel decoding (klauspost): https://github.com/celestiaorg/rsmt2d/blob/parallelisation_klauspost/extendeddatacrossword.go#L73

klauspost leopard:
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkRepair/RSGF8_4x4x256_ODS-16         	--- FAIL: BenchmarkRepair/RSGF8_4x4x256_ODS-16
    extendeddatacrossword_test.go:217: byzantine row: 3
BenchmarkRepair/LeopardFF8_4x4x256_ODS-16    	     518	   2273441 ns/op
BenchmarkRepair/LeopardFF16_4x4x256_ODS-16   	     499	   2318601 ns/op
BenchmarkRepair/RSGF8_8x8x256_ODS-16         	--- FAIL: BenchmarkRepair/RSGF8_8x8x256_ODS-16
    extendeddatacrossword_test.go:217: byzantine row: 7
BenchmarkRepair/LeopardFF8_8x8x256_ODS-16    	     300	   3929318 ns/op
BenchmarkRepair/LeopardFF16_8x8x256_ODS-16   	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5781d4]

goroutine 436131 [running]:
github.com/klauspost/reedsolomon.mulgf16_avx2({0xc0092c6d00, 0x100, 0x100}, {0x0, 0x100, 0x100}, 0xc0048ccc80)
	/home/mus/go/pkg/mod/github.com/klauspost/reedsolomon@v1.11.0/galois_gen_amd64.s:63559 +0x54
github.com/klauspost/reedsolomon.mulgf16({0xc0092c6d00?, 0x10?, 0x10?}, {0x0?, 0x100?, 0xc000280000?}, 0xffff?, 0x0?)
	/home/mus/go/pkg/mod/github.com/klauspost/reedsolomon@v1.11.0/galois_amd64.go:336 +0x6d
github.com/klauspost/reedsolomon.(*leopardFF16).reconstruct(0xc00011c000, {0xc006300300, 0x10?, 0x10?}, 0x1)
	/home/mus/go/pkg/mod/github.com/klauspost/reedsolomon@v1.11.0/leopard.go:456 +0x7fa
github.com/klauspost/reedsolomon.(*leopardFF16).Reconstruct(0x203001?, {0xc006300300?, 0x203001?, 0xc006300300?})
	/home/mus/go/pkg/mod/github.com/klauspost/reedsolomon@v1.11.0/leopard.go:315 +0x25
github.com/celestiaorg/rsmt2d.decode({0xc006300300, 0x10, 0x10})
	/home/mus/Code/rsmt2d/leopard.go:62 +0xf8
github.com/celestiaorg/rsmt2d.leoRSFF16Codec.Decode(...)
	/home/mus/Code/rsmt2d/leopard.go:81
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).rebuildShares(0xc000078000, 0x1, {0xc006300300?, 0x10, 0x10})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:259 +0x58
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrosswordCol(0xc000078000, 0x2, {0xc006300600, 0x10, 0x10}, {0xc006300780, 0x10, 0x10})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:218 +0x1f3
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrossword.func2()
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:102 +0x4f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/mus/go/pkg/mod/golang.org/x/sync@v0.0.0-20220907140024-f12130a52804/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/mus/go/pkg/mod/golang.org/x/sync@v0.0.0-20220907140024-f12130a52804/errgroup/errgroup.go:72 +0xa5
exit status 2
FAIL	github.com/celestiaorg/rsmt2d	6.506s
```

go-leopard:
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkRepair/Repairing_16x16_ODS_using_LeopardFF16-16         	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46ae98]

goroutine 6166 [running]:
github.com/celestiaorg/go-leopard._Cfunc_CBytes(...)
	_cgo_gotypes.go:46
github.com/celestiaorg/go-leopard.copyByteBuffer.func1({0x0, 0x100, 0xc000500001?})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:215 +0x85
github.com/celestiaorg/go-leopard.copyByteBuffer({0x0?, 0xc00022dbc8?, 0x44f9d2?})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:215 +0x25
github.com/celestiaorg/go-leopard.copyToCmallocedPtrs({0xc0003c0600, 0x10, 0x0?})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:208 +0x85
github.com/celestiaorg/go-leopard.Recover({0xc0003c0600?, 0x10, 0x20}, {0xc0003c0780?, 0x10, 0x10})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:127 +0x36a
github.com/celestiaorg/go-leopard.Decode({0xc0003c0600?, 0x10, 0x4205e0?}, {0xc0003c0780?, 0x10, 0xc0006ef670?})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:160 +0x3b
github.com/celestiaorg/rsmt2d.leoRSFF16Codec.Decode({}, {0xc0003c0600?, 0x300?, 0x0?})
	/home/mus/Code/rsmt2d/leopard.go:45 +0x54
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).rebuildShares(0xc0000e8060, 0x1, {0xc0003c0600?, 0x20, 0x20})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:259 +0x58
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrosswordRow(0xc0000e8060, 0x1a, {0xc000582000, 0x20, 0x20}, {0xc000582300, 0x20, 0x20})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:156 +0x1d4
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrossword.func1()
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:91 +0x4f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/mus/go/pkg/mod/golang.org/x/sync@v0.0.0-20220907140024-f12130a52804/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/mus/go/pkg/mod/golang.org/x/sync@v0.0.0-20220907140024-f12130a52804/errgroup/errgroup.go:72 +0xa5
exit status 2
FAIL	github.com/celestiaorg/rsmt2d	0.101s
```

_Originally posted by @musalbas in https://github.com/celestiaorg/rsmt2d/issues/116#issuecomment-1248117819_

We should investigate and potentially fix the leopard klauspost leopard implementation so that we can use it to repair the square in a parallelized way.

**Comment by musalbas** [comment]
cc @elias-orijtech

**Comment by rahulghangas** [comment]
It seems there are multiple race conditions within the parallel implementation as well

**Comment by musalbas** [comment]
Where? Can you open an issue describing the race conditions?

**Comment by rootulp** [comment]
I attempted to reproduce this and could not. On closer inspection of the stack traces in the issue body, the crashes were caused by data races in the (since-deleted) `parallelisation_klauspost` branch itself — not by the klauspost leopard implementation. Details below.

## Why this is not reproducible

**1. The stack traces show an impossible slice, which is the signature of a caller-side data race.**

In the klauspost crash, `mulgf16` received a shard of `{0x0, 0x100, 0x100}` — a slice with a **nil pointer but length 256**. The go-leopard crash shows the same pattern (`copyByteBuffer({0x0, 0x100, ...})`). A nil-pointer slice with non-zero length cannot be constructed in race-free Go. It is the classic signature of a *torn slice-header read*: one goroutine reads `shards[i]` while another concurrently writes `shards[i] = nil` (a slice header assignment is a multi-word write and is not atomic). In other words, the `[][]byte` passed to `Decode` was being mutated by another goroutine mid-reconstruction.

That is exactly what the parallel crossword branch did: every cell of the square belongs to both a row vector and a column vector, `Reconstruct` fills in missing shards of its input in place, and the branch ran row and column solvers concurrently over vectors sharing the same cells without synchronization.

**2. The benchmark output in the issue body shows the same race corrupting the *other* codec.**

In the very same run, the infectious codec (`RSGF8`) didn't segfault but failed with `byzantine row: 3` / `byzantine row: 7` — silent data corruption, which is the other typical outcome of the same race. So all three codecs were misbehaving in that run; leopard just happened to crash loudly instead of producing wrong data. This also matches https://github.com/celestiaorg/rsmt2d/issues/123#issuecomment-1253371597 ("there are multiple race conditions within the parallel implementation as well").

**3. Concurrent decoding through the codec works fine when each goroutine owns its input.**

I ran the test below under `go test -race -count=10`, exercising both the leopard GF8 (≤256 total shards) and leopard GF16 (>256 total shards) code paths against klauspost/reedsolomon **v1.14.0** (the version rsmt2d uses today). I also ran an equivalent test against **v1.11.0** — the exact version from the original report, with a shared `reedsolomon.New(256, 256, WithLeopardGF16(true))` encoder reconstructing from 16 goroutines. Every run passed with no crashes and no race-detector reports.

<details>
<summary>Reproduction test (passes under <code>-race</code>)</summary>

```go
func TestLeoRSCodecConcurrentDecode(t *testing.T) {
	codec := NewLeoRSCodec()

	testCases := []struct {
		name       string
		dataShares int
	}{
		{"leopardFF8", 16},   // 32 total shards <= 256 so leopard GF8 is used
		{"leopardFF16", 256}, // 512 total shards > 256 so leopard GF16 is used
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			original := generateRandData(tc.dataShares, shareSize)
			parity, err := codec.Encode(original)
			require.NoError(t, err)

			extended := make([][]byte, 0, tc.dataShares*2)
			extended = append(extended, original...)
			extended = append(extended, parity...)

			const numGoroutines = 16
			const iterations = 8

			var wg sync.WaitGroup
			for g := 0; g < numGoroutines; g++ {
				wg.Add(1)
				go func(seed int64) {
					defer wg.Done()
					rng := rand.New(rand.NewSource(seed))
					for i := 0; i < iterations; i++ {
						// Each goroutine decodes its own copy of the extended
						// data with a random half of the shares erased. Only
						// the codec (and its cached encoder) is shared.
						missing := make([][]byte, len(extended))
						for j, share := range extended {
							missing[j] = append([]byte(nil), share...)
						}
						for _, idx := range rng.Perm(len(missing))[:tc.dataShares] {
							missing[idx] = nil
						}

						decoded, err := codec.Decode(missing)
						if err != nil {
							t.Errorf("Decode() error: %v", err)
							return
						}
						for j, share := range original {
							if !bytes.Equal(decoded[j], share) {
								t.Errorf("decoded share %d differs from original", j)
								return
							}
						}
					}
				}(int64(g))
			}
			wg.Wait()
		})
	}
}
```

</details>

## Conclusion

The klauspost leopard implementation handles parallel decoding correctly; the failures came from the parallelisation branch racing on the shares of the square that row and column vectors have in common. That branch has been deleted, so there is nothing left to fix here. If `Repair` is parallelized in the future, the implementation must ensure row/column goroutines don't concurrently read and write the same cells (e.g. decode on copies and synchronize writes back to the square) — the codec itself is not the obstacle.

Closing as not reproducible.
